[profile.default]
src = 'contracts'
out = 'out'
libs = ["lib", "node_modules"]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
    'solidity-bytes-utils/=node_modules/solidity-bytes-utils/',
    '@chainlink/=node_modules/@chainlink/',
    '@eth-optimism/=node_modules/@eth-optimism/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'chainlink/=lib/chainlink/contracts/src/v0.8/dev/vendor/@arbitrum/nitro-contracts/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'forge-std/=lib/forge-std/src/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'solidity-bytes-utils/=node_modules/solidity-bytes-utils/',
]
test = 'test/foundry'
cache_path  = 'forge-cache'

[DEPLOYER]
DEPLOYER = "${DEPLOYER}"

[rpc_endpoints]
goerli = "${GOERLI_RPC_ENDPOINT}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config